name: review_impl
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  review_core:
    path: '../core'

  # In-App review - https://pub.dev/packages/in_app_review
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

