name: sponsor_data_closed
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../../core'

  sponsor_core:
    path: '../core'

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Rx Dart - https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

  # In App Purchase - https://pub.dev/packages/in_app_purchase
  in_app_purchase: ^3.2.3
  in_app_purchase_android:
  in_app_purchase_storekit:

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
