name: report
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../core'

  station:
    path: '../station'

  # BLoC - https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^9.1.1

  # Rx Dart - https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

  # HTTP - https://pub.dev/packages/http
  http: ^1.6.0

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Intl - https://pub.dev/packages/intl
  intl: ^0.20.2

  # Collection - https://pub.dev/packages/collection
  collection: ^1.19.1

  # Easy Localization - https://pub.dev/packages/easy_localization
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
