name: map_google
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../../core'

  map_core:
    path: '../core'

  # Google Maps - https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.14.0
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

