name: core
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  settings:
    path: '../settings'

  # Package Info - https://pub.dev/packages/package_info_plus
  package_info_plus: ^9.0.0

  # Tuple - https://pub.dev/packages/tuple
  tuple: ^2.0.2

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Shared Preferences - https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.4

  # UUID - https://pub.dev/packages/uuid
  uuid: ^4.5.2

  # Logger - https://pub.dev/packages/logger
  logger: ^2.6.2

  # Path Provider - https://pub.dev/packages/path_provider
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/