name: sponsor_core
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../../core'

  # BLoC - https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^9.1.1

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Shared Preferences - https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

