name: location_impl
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../../core'

  navigation_core:
    path: '../../navigation/core'

  location_core:
    path: '../core'

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Location - https://pub.dev/packages/geolocator
  geolocator: ^14.0.1

  # HTTP - https://pub.dev/packages/http
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

