name: map
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../core'

  settings:
    path: '../settings'

  # BLoC - https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^9.1.1

  # Google Maps - https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.14.0
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:

  # Apple Maps - https://pub.dev/packages/apple_maps_flutter
  apple_maps_flutter: ^1.4.0

  # MapLibre - https://github.com/maplibre/flutter-maplibre-gl
  maplibre_gl: ^0.24.1
#    git:
#      url: https://github.com/fabi755/flutter-maplibre-gl.git
#      ref: feature/gradle-namespace

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Rx Dart - https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

  # Shared Preferences - https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.4

#dependency_overrides:
#  # Force `package_info_plus` using newest `web` version (see: https://github.com/fluttercommunity/plus_plugins/issues/2653)
#  web: ^0.5.0
#
#  # Force `flutter_localizations` using newest `intl`
#  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

