name: station
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../core'

  map:
    path: '../map/map'

  navigation:
    path: '../navigation/navigation'

  settings:
    path: '../settings'

  report:
    path: '../report'

  sponsor_ui:
    path: '../sponsor/ui'

  # BLoC - https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^9.1.1

  # Rx Dart - https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

  # HTTP - https://pub.dev/packages/http
  http: ^1.6.0

  # Google Maps - https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.14.0

  # Shared Preferences - https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.4

  # Location - https://pub.dev/packages/geolocator
  geolocator: ^14.0.1

  # In-App review - https://pub.dev/packages/in_app_review
  in_app_review: ^2.0.11

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

  # Intl - https://pub.dev/packages/intl
  intl: ^0.20.2

  # Collection - https://pub.dev/packages/collection
  collection: ^1.19.1

  # URL Launcher - https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.2

  # Easy Localization - https://pub.dev/packages/easy_localization
  easy_localization: ^3.0.8

  # Flutter Chart - https://pub.dev/packages/fl_chart
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
