name: map_maplibre
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../../core'

  map_core:
    path: '../core'

  # MapLibre - https://github.com/maplibre/flutter-maplibre-gl
  maplibre_gl: ^0.24.1

  # Multiple Result - https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

